### ISSUE TITLE
Binary or continuous gene matrix?

### ISSUE THREAD

**Issue by cgcess** [JialongJiang/DSPIN#2]
A quick question about the oNMF implementation. In the comments for compute_onmf(), it says that it takes in a "Binary Matrix representing the gene expression data.", however when implemented in compute_onmf_repeats(), the normalized matrix appears to be continuous. Is this just a left-over comment from a previous version, should oNMF in fact be calculated on a binary matrix, or does it not matter if the gene matrix is binarized or continuous?

Thanks.

**Comment by JialongJiang** [comment]
Thank you for the comments. The input matrix should be continuous. This was a leftover from previous versions and I'll correct it. Also, I recommend normalizing each gene by its std as in the dspin code to balance expression level.
